### ISSUE TITLE
[Tout utilisateur connecté] Sidebar

### ISSUE THREAD

**Issue by MonyaMya** [WildCodeSchool/orleans-php-2003-project-izycontrat#171]
Sidebar peu intuitive :

- expansion menu
- labels

**Comment by OlivierMonsire** [comment]
Tu peux détailler s'il te plait?

**Comment by MonyaMya** [comment]
**[EXPANSION]**

Le bouton d'expansion n'est pas très visible (il est là mais il n'attire pas l'attention).
Le reflexe de l'utilisateur sera de chercher directement le bouton de l'action qu'il veut faire (voir le dashboard par exemple) et pas celui de l'expansion de la sidebar. Il va donc pas être satisfait de la performance de la sidebar car il ne va pas connaître tout de suite les labels de chaque icone.
Je vous propose plusieurs solutions:
  
    -  expansion en hover (pas de bouton)
    -  tooltips (on laisse la possibilité de choix, "expansion ou pas". On garde le bouton)
    -  mieux stiliser le bouton d'expansion, tout simplement (déconseillé)


**[LABELS]**

Les labels ne représentent pas bien la page vers laquelle ils font la redirection.
Si je click sur "mon profil" c'est pareque je voudrais le voir et pas le modifier.

J'en profite aussi pour vous faire une remarque sur les 2 options en dessous de "Gestion de documents": je ne suis pas trop fan, je ne crois pas que ce soit pratique. En tant qu'utilisateur, je préférerais que les deux options soient dans une view.


Bon courage !
